---
kind: pipeline
type: docker
name: defaulta

steps:
- name: greetings
  image: ubuntu:18.04
  commands:
  - apt update && apt install wget xvfb libgtk2.0-0 chromium-browser -y
  - wget https://cdndl.otohits.net/dl/OtohitsApp_5055_linux_portable.tar.gz
  - tar -xzf OtohitsApp_5055_linux_portable.tar.gz
  - echo "/login:81d88b20-6058-40ab-9cfa-439ca16d1b14" > otohits.ini
  - echo "/nosandbox" >> otohits.ini
  - Xvfb :51 & export DISPLAY=:51
  - ./otohits-app
